updated to gettext 0.18.3

diff --git a/source/gettext-tools/tests/gettext-7 b/source/gettext-tools/tests/gettext-7
--- a/source/gettext-tools/tests/gettext-7
+++ b/source/gettext-tools/tests/gettext-7
@@ -7,46 +7,49 @@
 tmpfiles=""
 trap 'rm -fr $tmpfiles' 1 2 3 15
 
-# This test works only on glibc systems.
+# This test works only on glibc and MacOS X systems.
+: ${host_os=unknown}
 : ${GLIBC2=no}
-test "$GLIBC2" = yes || {
-  echo "Skipping test: not a glibc system"
+{ case "$host_os" in
+    *-gnu*) test "$GLIBC2" = yes ;;
+    darwin*) true ;;
+    *) false ;;
+  esac
+} || {
+  echo "Skipping test: not a glibc or Mac OS X system"
   exit 77
 }
 
 # This test works only on systems that have a de_DE.ISO-8859-1 and
 # de_DE.UTF-8 locale installed.
-LC_ALL=de_DE.ISO-8859-1 ./testlocale || {
+missing_locale=`./gettext-7-prg 1`
+if test -n "$missing_locale"; then
   if test -f /usr/bin/localedef; then
-    echo "Skipping test: locale de_DE.ISO-8859-1 not installed"
+    echo "Skipping test: locale ${missing_locale} not installed"
   else
-    echo "Skipping test: locale de_DE.ISO-8859-1 not supported"
+    echo "Skipping test: locale ${missing_locale} not supported"
   fi
   exit 77
-}
-LC_ALL=de_DE.UTF-8 ./testlocale || {
-  if test -f /usr/bin/localedef; then
-    echo "Skipping test: locale de_DE.UTF-8 not installed"
-  else
-    echo "Skipping test: locale de_DE.UTF-8 not supported"
-  fi
-  exit 77
-}
+fi
 
-tmpfiles="$tmpfiles de_DE"
-test -d de_DE || mkdir de_DE
-test -d de_DE/LC_MESSAGES || mkdir de_DE/LC_MESSAGES
+tmpfiles="$tmpfiles gt-7"
+test -d gt-7 || mkdir gt-7
+test -d gt-7/de_DE || mkdir gt-7/de_DE
+test -d gt-7/de_DE/LC_MESSAGES || mkdir gt-7/de_DE/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o de_DE/LC_MESSAGES/tstthread.mo ${top_srcdir}/tests/gettext-7.po
+${MSGFMT} -o gt-7/de_DE/LC_MESSAGES/tstthread.mo ${top_srcdir}/tests/gettext-7.po
 
 tmpfiles="$tmpfiles gt-7.out"
 ./gettext-7-prg > gt-7.out
 case $? in
   0) ;;
   77)
-    echo "Skipping test: not a glibc 2.3 system"
+    echo "Skipping test: not a glibc >= 2.3 or MacOS X >= 10.5 system"
     rm -fr $tmpfiles; exit 77
+    ;;
+  *)
+    exit 1
     ;;
 esac
 
diff --git a/source/gettext-tools/tests/msgexec-4 b/source/gettext-tools/tests/msgexec-4
--- a/source/gettext-tools/tests/msgexec-4
+++ b/source/gettext-tools/tests/msgexec-4
@@ -2,6 +2,19 @@
 
 # Test msgexec on a PO file with contexts.
 
+# This test fails on mingw (in a Cygwin environment), due to the combination
+# of two reasons:
+# 1. The value of the environment variable MSGEXEC_MSGCTXT is stored
+#    in UTF-8 encoding (i.e. the PO file's encoding); it should be stored
+#    in the GetACP() encoding instead. This problem is inherent in msgexec,
+#    and msgexec warns about it - but in this test, we filter the warnings
+#    away.
+# 2. The child process is Cygwin's sh.exe, and is affected by a Cygwin bug:
+#    the values returned by getenv() in the child process, when the parent
+#    process is a mingw program, are in the GetOEMCP() encoding (should be
+#    in the GetACP() encoding). This has been reported at
+#    <http://cygwin.com/ml/cygwin/2009-08/msg00430.html>.
+
 tmpfiles=""
 trap 'rm -fr $tmpfiles' 1 2 3 15
 
@@ -54,24 +67,27 @@ EOF
 tmpfiles="$tmpfiles mex-test4.sh"
 cat <<\EOF > mex-test4.sh
 #! /bin/sh
-echo "========================= $MSGEXEC_LOCATION ========================="
+echo "========================= $MSGEXEC_LOCATION =========================" | LC_ALL=C tr -d '\r'
 if test -n "${MSGEXEC_MSGCTXT+set}"; then
-  echo "context: $MSGEXEC_MSGCTXT"
+  echo "context: $MSGEXEC_MSGCTXT" | LC_ALL=C tr -d '\r'
 fi
 cat <<MEOF
 $MSGEXEC_MSGID
 ---
 MEOF
 cat
-echo
+echo | LC_ALL=C tr -d '\r'
 exit 0
 EOF
 chmod a+x mex-test4.sh
 
-tmpfiles="$tmpfiles mex-test4.out"
+tmpfiles="$tmpfiles mex-test4.out mex-test4.err"
 : ${MSGEXEC=msgexec}
-${MSGEXEC} -i mex-test4.po ./mex-test4.sh > mex-test4.out
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C \
+${MSGEXEC} -i mex-test4.po ./mex-test4.sh > mex-test4.out 2> mex-test4.err
+result=$?
+cat mex-test4.err | grep -v 'warning: Locale charset' | grep -v '^ '
+test $result = 0 || { rm -fr $tmpfiles; exit 1; }
 
 tmpfiles="$tmpfiles mex-test4.ok"
 cat <<\EOF > mex-test4.ok
